---
# tasks file for hswong3i.apache2

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.apache2

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  tags: hswong3i.apache2

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  notify: restart apache2
  tags: hswong3i.apache2

- name: prepare file
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "/var/log/apache2", owner: "root", group: "adm", mode: "0711", state: "directory" }
    - { dest: "/var/log/apache2/vhosts", owner: "root", group: "adm", mode: "0711", state: "directory" }
  notify: restart apache2
  tags: hswong3i.apache2

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/apache2/apache2.conf.j2", dest: "/etc/apache2/apache2.conf", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/apache2/mods-available/remoteip.conf.j2", dest: "/etc/apache2/mods-available/remoteip.conf", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/apache2/ports.conf.j2", dest: "/etc/apache2/ports.conf", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/logrotate.d/apache2.j2", dest: "/etc/logrotate.d/apache2", owner: "root", group: "root", mode: "0644" }
  notify: restart apache2
  tags: hswong3i.apache2

- name: enable module
  apache2_module:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ (_apache2_module + apache2_module) | unique }}"
  notify: restart apache2
  tags: hswong3i.apache2

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "apache2", enabled: "yes" }
  notify: restart apache2
  tags: hswong3i.apache2
