---
# vars file for hswong3i.java (trusty)

_apt_repository: [
  { state: "present", repo: "ppa:webupd8team/java" },
]
_apt: [
  { state: "latest", name: "oracle-java8-installer" },
  { state: "latest", name: "oracle-java8-set-default" },
]
