---
# tasks file for hswong3i.confluence

- name: create group
  group:
    name: "{{ confluence_user }}"
    gid: "{{ confluence_gid | default(None) or omit }}"
  when: confluence_pass is string and confluence_hash_salt is string
  notify: restart confluence
  tags: hswong3i.confluence

- name: create user
  user:
    name: "{{ confluence_user }}"
    password: "{{ confluence_pass | password_hash('sha512', confluence_hash_salt) }}"
    home: "{{ confluence_home }}"
    group: "{{ confluence_user }}"
    uid: "{{ confluence_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: confluence_pass is string and confluence_hash_salt is string
  notify: restart confluence
  tags: hswong3i.confluence

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ confluence_catalina }}", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: "0755", state: "directory" }
  notify: restart confluence
  tags: hswong3i.confluence

- name: download package
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
  with_items:
    - { url: "{{ confluence_url }}", dest: "/tmp/{{ confluence_archive }}", checksum: "{{ confluence_checksum }}" }
  tags: hswong3i.confluence

- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ confluence_archive }} -C {{ confluence_catalina }} --strip-components=1
    chown -Rf {{ confluence_user }}:{{ confluence_user }} {{ confluence_catalina }}
  args:
    creates: "{{ confluence_catalina }}/bin/start-confluence.sh"
  notify: restart confluence
  tags: hswong3i.confluence

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/confluence.j2", dest: "/etc/init.d/confluence", owner: "root", group: "root", mode: "0755" }
    - { src: "usr/share/confluence/bin/setenv.sh.j2", dest: "{{ confluence_catalina }}/bin/setenv.sh", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: "0644" }
    - { src: "usr/share/confluence/conf/server.xml.j2", dest: "{{ confluence_catalina }}/conf/server.xml", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: "0644" }
  notify: restart confluence
  tags: hswong3i.confluence

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "confluence", enabled: "yes" }
  notify: restart confluence
  tags: hswong3i.confluence
