- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - madkiss.certificate
    - role: hswong3i.mysql_vhosts
      apache2_vhosts_id: "jira"
      apache2_vhosts_user: "jira"
    - role: hswong3i.jira
      apache2_vhosts_user: "jira"
      apache2_vhosts_server_name: "jira.example.net"
      apache2_vhosts_home: "/var/lib/jira"
    - role: hswong3i.mysql_connector_java
      mysql_connector_java_dest: "/usr/share/jira/lib"
      apache2_vhosts_user: "jira"
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ jira_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ jira_server_port }}", proto: "tcp", rule: "allow" }
    - role: hswong3i.apache2_vhosts
      apache2_vhosts_home: "/var/lib/jira"
      apache2_vhosts_id: "jira"
      apache2_vhosts_proxy_pass: "/   http://localhost:{{ jira_connector_port }}/"
      apache2_vhosts_proxy_pass_reverse: "/   http://localhost:{{ jira_connector_port }}/"
      apache2_vhosts_server_name: "jira.example.net"
      apache2_vhosts_user: "jira"
