- hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - hswong3i.mysql
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ mysql_port }}", proto: "tcp", rule: "allow" }
