---
# tasks file for hswong3i.tzdata

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "tzdata" }
  notify: update timezone
  tags: hswong3i.tzdata

- name: copy templates (trusty)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/timezone.j2", dest: "/etc/timezone",  owner: "root", group: "root", mode: "0644" }
  when: ansible_distribution_release == 'trusty'
  notify: update timezone
  tags: hswong3i.tzdata

- name: symlink file (xenial)
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_items:
    - { src: "/usr/share/zoneinfo/{{ tzdata_timezone }}", dest: "/etc/localtime", owner: "root", group: "root", state: "link" }
  when: ansible_distribution_release == 'xenial'
  notify: update timezone
  tags: hswong3i.tzdata
