---
# defaults file for hswong3i.confluence

# required variables
confluence_gid: ~
confluence_hash_salt: ~
confluence_pass: ~
confluence_uid: ~
confluence_user: ~

# optional variables with default
confluence_archive: "atlassian-confluence-6.3.1.tar.gz"
confluence_catalina: "/usr/share/confluence"
confluence_checksum: "sha256:2099d20b6b7b678f3be87972c656fad3cd65ae8517f5de56cafb454d3062f038"
confluence_connector_port: "8090"
confluence_context_path: ~
confluence_home: "/var/lib/confluence"
confluence_jvm_maximum_memory: "2048m"
confluence_jvm_minimum_memory: "1024m"
confluence_jvm_support_recommended_args: "-Datlassian.plugins.enable.wait=300"
confluence_proxy_name: ~
confluence_scheme: ~
confluence_server_port: "8000"
confluence_url: "https://downloads.atlassian.com/software/confluence/downloads/{{ confluence_archive }}"
