---
# tasks file for hswong3i.ntp

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "ntp" }
  notify: restart ntp
  tags: hswong3i.ntp

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
  - { dest: "/var/log/ntpstats", owner: "ntp", group: "ntp", mode: "0755", state: "directory" }
  notify: restart ntp
  tags: hswong3i.ntp

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/ntp.conf.j2", dest: "/etc/ntp.conf",  owner: "root", group: "root", mode: "0644" }
  notify: restart ntp
  tags: hswong3i.ntp

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "ntp", enabled: "yes" }
  notify: restart ntp
  tags: hswong3i.ntp
