---
# handlers file for hswong3i.confluence

- name: restart confluence
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "confluence", state: "restarted" }
