# handlers file for postfix
---
- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: new aliases
  command: newaliases

- name: new virtual aliases
  command: postmap /etc/postfix/virtual

- name: postmap sasl_passwd
  command: postmap hash:/etc/postfix/sasl_passwd

- name: postmap sender_canonical_maps
  command: postmap hash:/etc/postfix/sender_canonical_maps
