---
# tasks file for hswong3i.locales

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "locales" }
  notify: update locales
  tags: hswong3i.locales

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/default/locale.j2", dest: "/etc/default/locale",  owner: "root", group: "root", mode: "0644" }
  notify: update locales
  tags: hswong3i.locales
