---
# vars file for hswong3i.apt (trusty)

_apt_key: []
_apt_repository: [
  { state: "present", repo: "deb http://archive.canonical.com/ubuntu trusty partner" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty main" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty restricted" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty universe" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-backports main" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-backports multiverse" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-backports universe" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates restricted" },
  { state: "present", repo: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe" },
  { state: "present", repo: "deb http://extras.ubuntu.com/ubuntu trusty main" },
  { state: "present", repo: "deb http://security.ubuntu.com/ubuntu trusty-security main" },
  { state: "present", repo: "deb http://security.ubuntu.com/ubuntu trusty-security multiverse" },
  { state: "present", repo: "deb http://security.ubuntu.com/ubuntu trusty-security restricted" },
  { state: "present", repo: "deb http://security.ubuntu.com/ubuntu trusty-security universe" },
  { state: "present", repo: "deb-src http://archive.canonical.com/ubuntu trusty partner" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty main" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty multiverse" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty restricted" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty universe" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-backports main" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-backports multiverse" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-backports restricted" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-backports universe" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates main" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates restricted" },
  { state: "present", repo: "deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates universe" },
  { state: "present", repo: "deb-src http://extras.ubuntu.com/ubuntu trusty main" },
  { state: "present", repo: "deb-src http://security.ubuntu.com/ubuntu trusty-security main" },
  { state: "present", repo: "deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse" },
  { state: "present", repo: "deb-src http://security.ubuntu.com/ubuntu trusty-security restricted" },
  { state: "present", repo: "deb-src http://security.ubuntu.com/ubuntu trusty-security universe" },
  { state: "present", repo: "ppa:fkrull/deadsnakes-python2.7" },
]
_apt: [
  { state: "latest", name: "acpid" },
  { state: "latest", name: "adduser" },
  { state: "latest", name: "apport" },
  { state: "latest", name: "apport-symptoms" },
  { state: "latest", name: "apt" },
  { state: "latest", name: "apt-utils" },
  { state: "latest", name: "aptitude" },
  { state: "latest", name: "at" },
  { state: "latest", name: "base-files" },
  { state: "latest", name: "base-passwd" },
  { state: "latest", name: "bash" },
  { state: "latest", name: "bc" },
  { state: "latest", name: "bmon" },
  { state: "latest", name: "bsdutils" },
  { state: "latest", name: "busybox-initramfs" },
  { state: "latest", name: "byobu" },
  { state: "latest", name: "bzip2" },
  { state: "latest", name: "colordiff" },
  { state: "latest", name: "console-setup" },
  { state: "latest", name: "coreutils" },
  { state: "latest", name: "cpio" },
  { state: "latest", name: "cron" },
  { state: "latest", name: "curl" },
  { state: "latest", name: "dash" },
  { state: "latest", name: "debconf" },
  { state: "latest", name: "debconf-i18n" },
  { state: "latest", name: "debianutils" },
  { state: "latest", name: "dh-python" },
  { state: "latest", name: "diffutils" },
  { state: "latest", name: "dmsetup" },
  { state: "latest", name: "dpkg" },
  { state: "latest", name: "e2fslibs" },
  { state: "latest", name: "e2fsprogs" },
  { state: "latest", name: "eject" },
  { state: "latest", name: "ethtool" },
  { state: "latest", name: "file" },
  { state: "latest", name: "findutils" },
  { state: "latest", name: "fonts-ubuntu-font-family-console" },
  { state: "latest", name: "gawk" },
  { state: "latest", name: "gcc-4.8-base" },
  { state: "latest", name: "gcc-4.9-base" },
  { state: "latest", name: "git" },
  { state: "latest", name: "git-flow" },
  { state: "latest", name: "gnupg" },
  { state: "latest", name: "gpgv" },
  { state: "latest", name: "grep" },
  { state: "latest", name: "gzip" },
  { state: "latest", name: "hostname" },
  { state: "latest", name: "htop" },
  { state: "latest", name: "ifupdown" },
  { state: "latest", name: "init-system-helpers" },
  { state: "latest", name: "initramfs-tools" },
  { state: "latest", name: "initramfs-tools-bin" },
  { state: "latest", name: "initscripts" },
  { state: "latest", name: "insserv" },
  { state: "latest", name: "iproute2" },
  { state: "latest", name: "iputils-ping" },
  { state: "latest", name: "isc-dhcp-client" },
  { state: "latest", name: "isc-dhcp-common" },
  { state: "latest", name: "kbd" },
  { state: "latest", name: "keyboard-configuration" },
  { state: "latest", name: "klibc-utils" },
  { state: "latest", name: "kmod" },
  { state: "latest", name: "landscape-common" },
  { state: "latest", name: "language-pack-en-base" },
  { state: "latest", name: "less" },
  { state: "latest", name: "libacl1" },
  { state: "latest", name: "libapt-inst1.5" },
  { state: "latest", name: "libapt-pkg4.12" },
  { state: "latest", name: "libarchive-extract-perl" },
  { state: "latest", name: "libattr1" },
  { state: "latest", name: "libaudit-common" },
  { state: "latest", name: "libaudit1" },
  { state: "latest", name: "libblkid1" },
  { state: "latest", name: "libbsd0" },
  { state: "latest", name: "libbz2-1.0" },
  { state: "latest", name: "libc-bin" },
  { state: "latest", name: "libc6" },
  { state: "latest", name: "libcap2" },
  { state: "latest", name: "libcap2-bin" },
  { state: "latest", name: "libcgmanager0" },
  { state: "latest", name: "libcomerr2" },
  { state: "latest", name: "libcurl3" },
  { state: "latest", name: "libdb5.3" },
  { state: "latest", name: "libdbus-1-3" },
  { state: "latest", name: "libdebconfclient0" },
  { state: "latest", name: "libdevmapper1.02.1" },
  { state: "latest", name: "libdrm2" },
  { state: "latest", name: "libestr0" },
  { state: "latest", name: "libevent-2.0-5" },
  { state: "latest", name: "libexpat1" },
  { state: "latest", name: "libffi6" },
  { state: "latest", name: "libfribidi0" },
  { state: "latest", name: "libgc1c2" },
  { state: "latest", name: "libgcc1" },
  { state: "latest", name: "libgcrypt11" },
  { state: "latest", name: "libgdbm3" },
  { state: "latest", name: "libgnutls-openssl27" },
  { state: "latest", name: "libgnutls26" },
  { state: "latest", name: "libgpg-error0" },
  { state: "latest", name: "libgpm2" },
  { state: "latest", name: "libiw30" },
  { state: "latest", name: "libjpeg-progs" },
  { state: "latest", name: "libjson-c2" },
  { state: "latest", name: "libjson0" },
  { state: "latest", name: "libklibc" },
  { state: "latest", name: "libkmod2" },
  { state: "latest", name: "liblocale-gettext-perl" },
  { state: "latest", name: "liblockfile-bin" },
  { state: "latest", name: "liblockfile1" },
  { state: "latest", name: "liblog-message-simple-perl" },
  { state: "latest", name: "liblzma5" },
  { state: "latest", name: "libmagic1" },
  { state: "latest", name: "libmodule-pluggable-perl" },
  { state: "latest", name: "libmount1" },
  { state: "latest", name: "libmpdec2" },
  { state: "latest", name: "libncurses5" },
  { state: "latest", name: "libncursesw5" },
  { state: "latest", name: "libnewt0.52" },
  { state: "latest", name: "libnih-dbus1" },
  { state: "latest", name: "libnih1" },
  { state: "latest", name: "libnl-3-200" },
  { state: "latest", name: "libnl-genl-3-200" },
  { state: "latest", name: "libp11-kit0" },
  { state: "latest", name: "libpam-cap" },
  { state: "latest", name: "libpam-modules" },
  { state: "latest", name: "libpam-modules-bin" },
  { state: "latest", name: "libpam-runtime" },
  { state: "latest", name: "libpam0g" },
  { state: "latest", name: "libpcre3" },
  { state: "latest", name: "libpcsclite1" },
  { state: "latest", name: "libplymouth2" },
  { state: "latest", name: "libpng12-0" },
  { state: "latest", name: "libpod-latex-perl" },
  { state: "latest", name: "libpolkit-agent-1-0" },
  { state: "latest", name: "libpolkit-backend-1-0" },
  { state: "latest", name: "libpopt0" },
  { state: "latest", name: "libprocps3" },
  { state: "latest", name: "libpython-stdlib" },
  { state: "latest", name: "libpython2.7" },
  { state: "latest", name: "libpython2.7-minimal" },
  { state: "latest", name: "libpython2.7-stdlib" },
  { state: "latest", name: "libpython3-stdlib" },
  { state: "latest", name: "libpython3.4-minimal" },
  { state: "latest", name: "libpython3.4-stdlib" },
  { state: "latest", name: "libreadline5" },
  { state: "latest", name: "libreadline6" },
  { state: "latest", name: "libselinux1" },
  { state: "latest", name: "libsemanage-common" },
  { state: "latest", name: "libsemanage1" },
  { state: "latest", name: "libsepol1" },
  { state: "latest", name: "libsigsegv2" },
  { state: "latest", name: "libslang2" },
  { state: "latest", name: "libsqlite3-0" },
  { state: "latest", name: "libss2" },
  { state: "latest", name: "libssl1.0.0" },
  { state: "latest", name: "libstdc++6" },
  { state: "latest", name: "libtasn1-6" },
  { state: "latest", name: "libterm-ui-perl" },
  { state: "latest", name: "libtext-charwidth-perl" },
  { state: "latest", name: "libtext-iconv-perl" },
  { state: "latest", name: "libtext-soundex-perl" },
  { state: "latest", name: "libtext-wrapi18n-perl" },
  { state: "latest", name: "libtinfo5" },
  { state: "latest", name: "libudev1" },
  { state: "latest", name: "libusb-0.1-4" },
  { state: "latest", name: "libustr-1.0-1" },
  { state: "latest", name: "libuuid1" },
  { state: "latest", name: "locales" },
  { state: "latest", name: "lockfile-progs" },
  { state: "latest", name: "login" },
  { state: "latest", name: "logrotate" },
  { state: "latest", name: "logwatch" },
  { state: "latest", name: "lsb-base" },
  { state: "latest", name: "lsb-release" },
  { state: "latest", name: "lvm2" },
  { state: "latest", name: "mailutils" },
  { state: "latest", name: "makedev" },
  { state: "latest", name: "mawk" },
  { state: "latest", name: "memtest86+" },
  { state: "latest", name: "mime-support" },
  { state: "latest", name: "module-init-tools" },
  { state: "latest", name: "mount" },
  { state: "latest", name: "mountall" },
  { state: "latest", name: "multiarch-support" },
  { state: "latest", name: "ncurses-base" },
  { state: "latest", name: "ncurses-bin" },
  { state: "latest", name: "net-tools" },
  { state: "latest", name: "netbase" },
  { state: "latest", name: "netcat-openbsd" },
  { state: "latest", name: "nfs-common" },
  { state: "latest", name: "nmap" },
  { state: "latest", name: "nmon" },
  { state: "latest", name: "ntp" },
  { state: "latest", name: "ntpdate" },
  { state: "latest", name: "optipng" },
  { state: "latest", name: "passwd" },
  { state: "latest", name: "patch" },
  { state: "latest", name: "perl" },
  { state: "latest", name: "perl-base" },
  { state: "latest", name: "perl-modules" },
  { state: "latest", name: "plymouth" },
  { state: "latest", name: "policykit-1" },
  { state: "latest", name: "procps" },
  { state: "latest", name: "pwgen" },
  { state: "latest", name: "python" },
  { state: "latest", name: "python-apt" },
  { state: "latest", name: "python-chardet" },
  { state: "latest", name: "python-configobj" },
  { state: "latest", name: "python-debian" },
  { state: "latest", name: "python-gdbm" },
  { state: "latest", name: "python-minimal" },
  { state: "latest", name: "python-mysqldb" },
  { state: "latest", name: "python-openssl" },
  { state: "latest", name: "python-pam" },
  { state: "latest", name: "python-pkg-resources" },
  { state: "latest", name: "python-serial" },
  { state: "latest", name: "python-six" },
  { state: "latest", name: "python-twisted-bin" },
  { state: "latest", name: "python-twisted-core" },
  { state: "latest", name: "python-zope.interface" },
  { state: "latest", name: "python2.7" },
  { state: "latest", name: "python2.7-minimal" },
  { state: "latest", name: "python3" },
  { state: "latest", name: "python3-apport" },
  { state: "latest", name: "python3-minimal" },
  { state: "latest", name: "python3-newt" },
  { state: "latest", name: "python3-problem-report" },
  { state: "latest", name: "python3-pycurl" },
  { state: "latest", name: "python3-software-properties" },
  { state: "latest", name: "python3.4" },
  { state: "latest", name: "python3.4-minimal" },
  { state: "latest", name: "readline-common" },
  { state: "latest", name: "resolvconf" },
  { state: "latest", name: "rsyslog" },
  { state: "latest", name: "run-one" },
  { state: "latest", name: "screen" },
  { state: "latest", name: "sed" },
  { state: "latest", name: "sensible-utils" },
  { state: "latest", name: "snmp-mibs-downloader" },
  { state: "latest", name: "software-properties-common" },
  { state: "latest", name: "sshfs" },
  { state: "latest", name: "sudo" },
  { state: "latest", name: "sysv-rc" },
  { state: "latest", name: "sysvinit-utils" },
  { state: "latest", name: "tar" },
  { state: "latest", name: "tasksel" },
  { state: "latest", name: "tmux" },
  { state: "latest", name: "tzdata" },
  { state: "latest", name: "ubuntu-extras-keyring" },
  { state: "latest", name: "ubuntu-keyring" },
  { state: "latest", name: "ubuntu-minimal" },
  { state: "latest", name: "ucf" },
  { state: "latest", name: "udev" },
  { state: "latest", name: "unattended-upgrades" },
  { state: "latest", name: "unzip" },
  { state: "latest", name: "update-notifier-common" },
  { state: "latest", name: "upstart" },
  { state: "latest", name: "ureadahead" },
  { state: "latest", name: "util-linux" },
  { state: "latest", name: "vim" },
  { state: "latest", name: "vim-common" },
  { state: "latest", name: "vim-runtime" },
  { state: "latest", name: "vim-tiny" },
  { state: "latest", name: "w3m" },
  { state: "latest", name: "whiptail" },
  { state: "latest", name: "wireless-tools" },
  { state: "latest", name: "wpasupplicant" },
  { state: "latest", name: "xkb-data" },
  { state: "latest", name: "xz-utils" },
  { state: "latest", name: "zlib1g" },
]
